# For documentation on GitHub Actions Workflows, see:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: Format

on: [push, pull_request]

permissions:
  contents: read

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout
        with:
          # Only a single commit is fetched by default, for the ref/SHA that triggered the workflow.
          # Set fetch-depth: 0 to fetch all history for all branches and tags.
          fetch-depth: 0 # Needed for setuptools_scm to work correctly
      - run: pip install --user ruff
      - run: ruff format --check
