# For documentation on GitHub Actions Workflows, see:
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: MyPy

on: [ push, pull_request ]

permissions:
  contents: read

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # https://github.com/actions/checkout
      - uses: actions/setup-python@v5  # https://github.com/actions/setup-python
        with:
          python-version: 3.13
          allow-prereleases: true
          # Only a single commit is fetched by default, for the ref/SHA that triggered the workflow.
          # Set fetch-depth: 0 to fetch all history for all branches and tags.
          fetch-depth: 0 # Needed for setuptools_scm to work correctly
      - run: pip install -U --user pip mypy
      - run: mypy .
